---

- name: Install Packages
  package:
    name: "{{ item }}"
  with_items:
    - supervisor
    - libavahi-compat-libdnssd-dev
    - avahi-daemon
    - avahi-discover
    - libnss-mdns

- name: Install Homebridge
  npm:
    name: homebridge
    global: true
- name: Install Homebridge Plugins
  npm:
    name: "{{ item }}"
    global: true
  with_items: "{{ homebridge_plugins }}"
  when: homebridge_plugins is defined

- name: Start supervisor service
  service:
    name: supervisor
    state: started

- name: Add group
  group:
    name: "{{ homebridge_group }}"
    system: yes
  when: homebridge_manage_user

- name: Add user
  user:
    name: "{{ homebridge_user }}"
    group: "{{ homebridge_group }}"
    shell: /sbin/nologin
    system: yes
  when: homebridge_manage_user

- name: Create Homebridge directory
  file:
    path: "{{ homebridge_dir }}"
    state: directory
    owner: "{{ homebridge_user }}"
    group: "{{ homebridge_group }}"
    recurse: true

- meta: flush_handlers

